In [1]:
import numpy as np

In [2]:
size_matrix = 256

batch = size_matrix
num_feats = size_matrix
num_hidden = size_matrix

In [3]:
d = (np.random.rand(batch, num_feats) - 0.5) * 10
d = d.astype(np.float32)
display(d.shape, d.dtype, d)

(256, 256)

dtype('float32')

array([[-2.539453  ,  4.940956  , -0.4555195 , ..., -0.82446235,
         0.5382848 , -3.1873553 ],
       [ 4.3999104 ,  2.4401202 ,  3.2898018 , ..., -3.0649133 ,
        -2.3461926 ,  0.52654254],
       [ 3.8952093 ,  4.0630503 , -3.5493755 , ..., -1.3703289 ,
        -0.9685776 ,  1.3101958 ],
       ...,
       [ 2.8487728 ,  4.844904  , -1.4479586 , ...,  3.818957  ,
        -3.6727188 ,  2.0357127 ],
       [ 0.39385396,  1.410079  , -3.452866  , ...,  3.262866  ,
        -2.061948  ,  0.04282537],
       [ 3.3102965 , -0.77989876, -4.6262407 , ..., -3.8696914 ,
        -3.204907  , -1.7082325 ]], dtype=float32)

In [4]:
w = (np.random.rand(num_feats, num_hidden) - 0.5) * 10
w = w.astype(np.float32)
display(w.shape, w.dtype, w)

(256, 256)

dtype('float32')

array([[-2.3613155 ,  4.683778  ,  3.7024999 , ...,  3.1184776 ,
        -1.8552847 , -3.4599428 ],
       [-2.3865633 ,  2.1782577 ,  3.2795205 , ...,  1.3084387 ,
        -4.700418  , -1.852612  ],
       [ 3.9780166 , -3.951194  , -0.7816977 , ...,  2.057262  ,
        -4.0090113 , -4.5593257 ],
       ...,
       [-1.9489486 ,  1.8889638 ,  0.15646875, ...,  4.7236166 ,
        -4.088744  , -0.7804253 ],
       [-0.01630772,  4.537899  , -3.4607701 , ...,  2.0711904 ,
         0.9252075 , -4.090975  ],
       [-3.6973116 ,  4.325587  ,  4.5284142 , ...,  2.8463573 ,
        -1.2030648 ,  3.1765316 ]], dtype=float32)

In [5]:
b = (np.random.rand(num_hidden) - 0.5) * 10
b = b.astype(np.float32)
display(b.shape, b.dtype, b)

(256,)

dtype('float32')

array([ 1.407766  , -3.3664126 , -3.3056283 , -0.12875278, -4.3473816 ,
        0.8666507 ,  0.32348925,  3.6012397 , -0.7716849 , -1.4826493 ,
        0.6233863 , -4.2264547 , -4.617994  ,  1.3609908 ,  2.6859467 ,
        4.2029853 , -4.884234  , -1.2911754 ,  2.1371906 , -2.1484501 ,
       -3.8725963 , -4.425297  ,  4.435463  ,  3.8691993 ,  1.2908983 ,
        4.084453  ,  2.8424935 ,  2.2606564 ,  2.2570121 ,  3.7027059 ,
        0.39759287,  0.23678939,  3.1923342 ,  4.829185  , -4.409265  ,
       -0.13294923, -3.5165591 , -0.304353  ,  0.93639654,  1.8608962 ,
        4.8711314 , -3.494925  , -0.3719533 ,  3.8191743 ,  2.334317  ,
       -4.443295  ,  3.1194527 ,  0.8642818 ,  2.3942904 ,  3.530951  ,
       -2.7749999 ,  1.1531304 , -3.2490869 , -3.9997015 , -0.33812463,
       -2.987701  , -2.2632592 , -3.202813  ,  2.1412914 ,  1.6832392 ,
       -1.1018745 ,  1.4884366 ,  3.502812  , -2.746674  , -0.7927441 ,
        2.507943  ,  0.86329806, -2.7116103 ,  0.72598344,  1.96

In [6]:
np.save("d.npy", d)
np.save("w.npy", w)

# Importante salvare esplicitamente la trasposta in row_major (order=C)
np.save("fc1.weight.npy", np.copy(w.T, order='C'))

np.save("b.npy", b)
np.save("fc1.bias.npy", b)